export default function IntelligenceSection() {
  return (
    <section className="py-[clamp(4rem,10vw,7.5rem)] px-[clamp(1.25rem,5vw,2.5rem)] bg-[var(--bg-2)] border-t border-[var(--border)] border-b">
      <div className="max-w-[1320px] mx-auto">
        <div className="mb-12">
          <div className="font-mono text-[clamp(0.57rem,1.4vw,0.63rem)] tracking-[0.18em] uppercase text-[var(--teal)] flex items-center gap-[7px] mb-5">
            // What the system produces
          </div>
          <h2 className="font-cond text-[clamp(2.2rem,6vw,4.5rem)] font-bold leading-[0.95] uppercase text-[var(--text-1)] mb-4">
            Real outputs.<br />Not <span className="text-[var(--accent)]">dashboards.</span>
          </h2>
          <p className="text-[clamp(0.87rem,2vw,0.96rem)] text-[var(--text-2)] leading-[1.8] max-w-[52ch] mt-2">
            ViralClaw doesn't show you raw data. It interprets it and gives you something you can act on immediately
            — a brief, a recommendation, a content angle.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
          {/* YouTube Report */}
          <div className="bg-[var(--bg-2)] border border-[var(--border)] overflow-hidden">
            <div className="bg-[var(--bg-3)] px-[14px] py-[9px] flex items-center justify-between border-b border-[var(--border)]">
              <span className="font-mono text-[0.57rem] tracking-[0.12em] uppercase text-[var(--text-3)]">
                YouTube Intelligence Report — Finance Niche
              </span>
              <span className="font-mono text-[0.52rem] tracking-[0.08em] uppercase px-2 py-[2px] text-[var(--teal)] border border-[var(--teal-border)] bg-[var(--teal-dim)]">
                Generated by Trend Agent
              </span>
            </div>
            <div className="p-[1.2rem]">
              {[
                {
                  label: "Format Signal",
                  labelColor: "var(--cyan-light)",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      <strong className="text-[var(--text-1)] font-medium">"Reaction + data reveal"</strong> format is trending across finance channels.
                      Videos opening with a chart anomaly and cutting to creator reaction in first 3 seconds are averaging{" "}
                      <span className="text-[var(--green)]">3.2× retention</span> vs talking-head openers. Detected across{" "}
                      <strong className="text-[var(--text-1)] font-medium">23 channels</strong> in the last 14 days.
                      <div className="flex flex-wrap gap-1 mt-3">
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--green)] border border-[var(--green-border)] bg-[var(--green-dim)]">3.2× retention</span>
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--teal)] border border-[var(--teal-border)] bg-[var(--teal-dim)]">23 channels</span>
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--text-3)] border border-[var(--border-3)]">14-day window</span>
                      </div>
                    </div>
                  ),
                },
                {
                  label: "Upload Timing",
                  labelColor: "var(--cyan-light)",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      Top-performing uploads in this niche cluster around{" "}
                      <span className="text-[var(--teal)]">Tuesday and Thursday, 2–4pm EST</span>.
                      Channels publishing in this window show <span className="text-[var(--green)]">1.8× first-24h views</span> vs off-peak uploads.
                    </div>
                  ),
                },
                {
                  label: "Recommended Brief",
                  labelColor: undefined,
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      Based on your brand DNA and current niche signals:{" "}
                      <strong className="text-[var(--text-1)] font-medium">"Why the Fed's next move will surprise most investors"</strong>
                      {" "}— open with data chart anomaly, reaction cut, walkthrough. Estimated strong performance window:{" "}
                      <span className="text-[var(--accent)]">next 4 days</span>.
                      <div className="mt-3">
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--accent)] border border-[var(--accent-border)] bg-[var(--accent-dim)]">
                          Brief ready in Strategy Agent
                        </span>
                      </div>
                    </div>
                  ),
                },
              ].map((section, i, arr) => (
                <div
                  key={section.label}
                  className={`${i < arr.length - 1 ? "mb-5 pb-5 border-b border-[var(--border)]" : ""}`}
                >
                  <div
                    className="font-mono text-[0.55rem] tracking-[0.14em] uppercase text-[var(--text-3)] mb-2 flex items-center gap-1"
                    style={{ color: section.labelColor || undefined }}
                  >
                    <span style={{ color: section.labelColor || "var(--accent)" }}>▸</span>
                    {section.label}
                  </div>
                  {section.content}
                </div>
              ))}
            </div>
          </div>

          {/* Repurposing & Distribution */}
          <div className="bg-[var(--bg-2)] border border-[var(--border)] overflow-hidden">
            <div className="bg-[var(--bg-3)] px-[14px] py-[9px] flex items-center justify-between border-b border-[var(--border)]">
              <span className="font-mono text-[0.57rem] tracking-[0.12em] uppercase text-[var(--text-3)]">
                Repurposing Plan — Finance Niche
              </span>
              <span className="font-mono text-[0.52rem] tracking-[0.08em] uppercase px-2 py-[2px] text-[var(--accent)] border border-[var(--accent-border)] bg-[var(--accent-dim)]">
                Generated by Production Agent
              </span>
            </div>
            <div className="p-[1.2rem]">
              {[
                {
                  label: "Source Content",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      Long-form YouTube video detected as <span className="text-[var(--green)]">high performer</span> — 58% avg retention, 3.1× click-through vs channel average.{" "}
                      Production Agent has queued <span className="text-[var(--teal)]">5 derivative assets</span> for review.
                      <div className="flex flex-wrap gap-1 mt-3">
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--green)] border border-[var(--green-border)] bg-[var(--green-dim)]">58% retention</span>
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--teal)] border border-[var(--teal-border)] bg-[var(--teal-dim)]">5 assets ready</span>
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--amber)] border border-[rgba(245,158,11,0.25)] bg-[var(--amber-dim)]">Awaiting review</span>
                      </div>
                    </div>
                  ),
                },
                {
                  label: "Derivative Assets",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      <strong className="text-[var(--text-1)] font-medium">1.</strong> 60-second Short — hook + data reveal cut<br /><br />
                      <strong className="text-[var(--text-1)] font-medium">2.</strong> X thread — 8 posts, key insight breakdown<br /><br />
                      <strong className="text-[var(--text-1)] font-medium">3.</strong> LinkedIn post — professional framing, same data<br /><br />
                      <strong className="text-[var(--text-1)] font-medium">4–5.</strong> Instagram carousel + email newsletter snippet
                    </div>
                  ),
                },
                {
                  label: "Distribution Plan",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      Schedule window: <span className="text-[var(--accent)]">Wed–Thu this week</span>.{" "}
                      Short → YouTube Shorts, thread → <span className="text-[var(--teal)]">X</span>, post → <span className="text-[var(--teal)]">LinkedIn</span>.{" "}
                      Distribution Agent ready to execute on your approval.
                    </div>
                  ),
                },
              ].map((section, i, arr) => (
                <div
                  key={section.label}
                  className={`${i < arr.length - 1 ? "mb-5 pb-5 border-b border-[var(--border)]" : ""}`}
                >
                  <div className="font-mono text-[0.55rem] tracking-[0.14em] uppercase text-[var(--text-3)] mb-2 flex items-center gap-1">
                    <span className="text-[var(--accent)]">▸</span>
                    {section.label}
                  </div>
                  {section.content}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
