export default function IntelligenceSection() {
  return (
    <section className="py-[clamp(4rem,10vw,7.5rem)] px-[clamp(1.25rem,5vw,2.5rem)] bg-[var(--bg-2)] border-t border-[var(--border)] border-b">
      <div className="max-w-[1320px] mx-auto">
        <div className="mb-12">
          <div className="font-mono text-[clamp(0.57rem,1.4vw,0.63rem)] tracking-[0.18em] uppercase text-[var(--teal)] flex items-center gap-[7px] mb-5">
            // What the system delivers
          </div>
          <h2 className="font-cond text-[clamp(2.2rem,6vw,4.5rem)] font-bold leading-[0.95] uppercase text-[var(--text-1)] mb-4">
            Two outputs.<br />One <span className="text-[var(--accent)]">intelligence layer.</span>
          </h2>
          <p className="text-[clamp(0.87rem,2vw,0.96rem)] text-[var(--text-2)] leading-[1.8] max-w-[52ch] mt-2">
            ViralClaw doesn't surface raw data. It interprets multi-signal intelligence — on-chain
            flows, social velocity, narrative momentum — and delivers two distinct actionable outputs:
            alpha for degens and content intelligence for creators.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-5 lg:grid-cols-2">
          {/* Degen Alpha Output */}
          <div className="bg-[var(--bg-2)] border border-[var(--border)] overflow-hidden">
            <div className="bg-[var(--bg-3)] px-[14px] py-[9px] flex items-center justify-between border-b border-[var(--border)]">
              <span className="font-mono text-[0.57rem] tracking-[0.12em] uppercase text-[var(--text-3)]">
                Alpha Brief — Cross-Ecosystem Degen
              </span>
              <span className="font-mono text-[0.52rem] tracking-[0.08em] uppercase px-2 py-[2px] text-[var(--accent)] border border-[var(--accent-border)] bg-[var(--accent-dim)]">
                Generated by Signal Engine
              </span>
            </div>
            <div className="p-[1.2rem]">
              {[
                {
                  label: "Trend Detection",
                  labelColor: "var(--cyan-light)",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      <strong className="text-[var(--text-1)] font-medium">Whale cluster accumulating</strong> EigenLayer-adjacent tokens across ETH + ARB.
                      On-chain signals detected{" "}
                      <span className="text-[var(--green)]">4.7h before social narrative peaked</span>.
                      Correlated across <strong className="text-[var(--text-1)] font-medium">3 ecosystems</strong>.
                      <div className="flex flex-wrap gap-1 mt-3">
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--green)] border border-[var(--green-border)] bg-[var(--green-dim)]">Score: 9.4</span>
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--teal)] border border-[var(--teal-border)] bg-[var(--teal-dim)]">23 wallets</span>
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--text-3)] border border-[var(--border-3)]">3 chains</span>
                      </div>
                    </div>
                  ),
                },
                {
                  label: "Cross-Chain Correlation",
                  labelColor: "var(--cyan-light)",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      Liquidity rotation detected from ETH mainnet →{" "}
                      <span className="text-[var(--teal)]">Base + Arbitrum</span>.
                      Bridge volume up <span className="text-[var(--green)]">340% in 6h</span> vs 30-day avg.
                      Pattern matches 3 prior rotation events.
                    </div>
                  ),
                },
                {
                  label: "Participation Alpha",
                  labelColor: undefined,
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      Conviction: <strong className="text-[var(--text-1)] font-medium">High</strong>.
                      Estimated participation window:{" "}
                      <span className="text-[var(--accent)]">next 12–24h before crowd arrives</span>.
                      Entry vectors and risk context included in full brief.
                      <div className="mt-3">
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--accent)] border border-[var(--accent-border)] bg-[var(--accent-dim)]">
                          Alpha brief ready
                        </span>
                      </div>
                    </div>
                  ),
                },
              ].map((section, i, arr) => (
                <div
                  key={section.label}
                  className={`${i < arr.length - 1 ? "mb-5 pb-5 border-b border-[var(--border)]" : ""}`}
                >
                  <div
                    className="font-mono text-[0.55rem] tracking-[0.14em] uppercase text-[var(--text-3)] mb-2 flex items-center gap-1"
                    style={{ color: section.labelColor || undefined }}
                  >
                    <span style={{ color: section.labelColor || "var(--accent)" }}>▸</span>
                    {section.label}
                  </div>
                  {section.content}
                </div>
              ))}
            </div>
          </div>

          {/* Creator Content Output */}
          <div className="bg-[var(--bg-2)] border border-[var(--border)] overflow-hidden">
            <div className="bg-[var(--bg-3)] px-[14px] py-[9px] flex items-center justify-between border-b border-[var(--border)]">
              <span className="font-mono text-[0.57rem] tracking-[0.12em] uppercase text-[var(--text-3)]">
                Content Intelligence — Web3 Creator
              </span>
              <span className="font-mono text-[0.52rem] tracking-[0.08em] uppercase px-2 py-[2px] text-[var(--teal)] border border-[var(--teal-border)] bg-[var(--teal-dim)]">
                Generated by Trend Engine
              </span>
            </div>
            <div className="p-[1.2rem]">
              {[
                {
                  label: "Narrative Intelligence",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      Restaking narrative detected <span className="text-[var(--green)]">on-chain first</span>,
                      now surfacing socially. Posts covering this angle averaging{" "}
                      <span className="text-[var(--teal)]">12× engagement</span> vs baseline.
                      Narrative origin: <strong className="text-[var(--text-1)] font-medium">ETH smart money wallets</strong>.
                      <div className="flex flex-wrap gap-1 mt-3">
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--green)] border border-[var(--green-border)] bg-[var(--green-dim)]">12× engagement</span>
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--teal)] border border-[var(--teal-border)] bg-[var(--teal-dim)]">On-chain verified</span>
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--text-3)] border border-[var(--border-3)]">Window: 18–36h</span>
                      </div>
                    </div>
                  ),
                },
                {
                  label: "Content Angles",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      <strong className="text-[var(--text-1)] font-medium">1.</strong> "The wallets that moved first — what the ETH smart money is doing now"<br /><br />
                      <strong className="text-[var(--text-1)] font-medium">2.</strong> "Why restaking is the narrative you can't ignore this week"<br /><br />
                      <strong className="text-[var(--text-1)] font-medium">3.</strong> Thread: on-chain evidence breakdown for your audience
                    </div>
                  ),
                },
                {
                  label: "Publish Window",
                  content: (
                    <div className="text-[clamp(0.82rem,1.8vw,0.9rem)] text-[var(--text-2)] leading-[1.7]">
                      Optimal publish:{" "}
                      <span className="text-[var(--accent)]">next 18–36h before narrative saturates</span>.
                      Full brief with sources, angle variants, and thread outline ready to ship.
                      <div className="mt-3">
                        <span className="font-mono text-[0.56rem] px-2 py-[3px] text-[var(--teal)] border border-[var(--teal-border)] bg-[var(--teal-dim)]">
                          Content brief ready
                        </span>
                      </div>
                    </div>
                  ),
                },
              ].map((section, i, arr) => (
                <div
                  key={section.label}
                  className={`${i < arr.length - 1 ? "mb-5 pb-5 border-b border-[var(--border)]" : ""}`}
                >
                  <div className="font-mono text-[0.55rem] tracking-[0.14em] uppercase text-[var(--text-3)] mb-2 flex items-center gap-1">
                    <span className="text-[var(--teal)]">▸</span>
                    {section.label}
                  </div>
                  {section.content}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
