"use client";

import { useState } from "react";

type Tab = "all" | "review" | "approved" | "published";

export default function ContentPage() {
  const [tab, setTab] = useState<Tab>("all");

  return (
    <div className="max-w-[1200px] mx-auto space-y-6">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="font-cond text-[clamp(1.5rem,4vw,2.2rem)] font-bold uppercase leading-none text-[var(--white)] tracking-[0.02em]">
            Content
          </h1>
          <p className="text-[0.78rem] text-[var(--low)] mt-2 font-light">
            Content assets generated by agents appear here for review before publishing.
          </p>
        </div>
        <button
          type="button"
          disabled
          className="font-mono text-[0.55rem] tracking-[0.12em] uppercase text-[var(--dim)] bg-[var(--surface)] border border-[var(--border)] px-4 py-2 cursor-not-allowed"
        >
          New brief →
        </button>
      </div>

      {/* Filter tabs */}
      <div className="flex gap-0 border-b border-[var(--border)]">
        {(["all", "review", "approved", "published"] as Tab[]).map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => setTab(t)}
            className={`font-mono text-[0.52rem] tracking-[0.1em] uppercase px-4 py-2 border-b-2 transition-colors ${
              tab === t
                ? "border-[var(--crimson)] text-[var(--white)]"
                : "border-transparent text-[var(--low)] hover:text-[var(--body)]"
            }`}
          >
            {t}
          </button>
        ))}
      </div>

      {/* Empty state */}
      <div className="border border-[var(--border)] overflow-hidden">
        <div className="bg-[var(--carbon)] flex flex-col items-center justify-center py-20 px-6 text-center">
          <div className="w-8 h-8 border border-[var(--border)] flex items-center justify-center mb-4">
            <span className="text-[var(--dim)] text-[0.9rem]">◻</span>
          </div>
          <p className="font-mono text-[0.57rem] tracking-[0.08em] uppercase text-[var(--low)] mb-2">
            No content yet
          </p>
          <p className="font-mono text-[0.52rem] text-[var(--dim)] leading-[1.65] max-w-[40ch]">
            Content assets will appear here once the Production Agent is running and a mission has been submitted.
          </p>
        </div>
      </div>

      {/* How the review flow works */}
      <div className="border border-[var(--border)] overflow-hidden">
        <div className="bg-[var(--surface)] px-4 py-2 border-b border-[var(--border)]">
          <span className="font-mono text-[0.52rem] tracking-[0.12em] uppercase text-[var(--low)]">
            Review flow
          </span>
        </div>
        <div className="bg-[var(--carbon)] divide-y divide-[var(--border)]">
          {[
            { status: "draft",     color: "var(--low)",       desc: "Agent has generated the asset but it has not been submitted for review" },
            { status: "review",    color: "var(--amber)",     desc: "Ready for your review — approve or edit before it moves forward" },
            { status: "approved",  color: "var(--green)",     desc: "You approved it — Distribution Agent will schedule this" },
            { status: "published", color: "var(--cyan-light)",desc: "Live on platform. Analytics Agent begins tracking at 24h" },
          ].map((row) => (
            <div key={row.status} className="px-4 py-3 flex items-center gap-4">
              <span
                className="font-mono text-[0.48rem] tracking-[0.08em] uppercase px-2 py-[2px] border shrink-0 w-[80px] text-center"
                style={{ color: row.color, borderColor: row.color + "44", background: row.color + "11" }}
              >
                {row.status}
              </span>
              <span className="font-mono text-[0.52rem] text-[var(--muted)]">{row.desc}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
